version: "3.8"
services:
  postgres:
    image: postgres:${POSTGRES_VERSION}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:${POSTGRES_PORT}"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/${PGADMIN_VERSION}
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5050:${PGADMIN_PORT}"
    depends_on:
      - postgres

volumes:
  pgdata:
